### ISSUE TITLE
Feature Request:  add lintr options

### ISSUE THREAD

**Issue by nicholas-masel** [atorus-research/logrx#102]
### Feature Idea

Allow users to specify [linters](https://lintr.r-lib.org/reference/linters.html), capture results from lint and store in log section.

### Relevant Input

A list of [linters](https://lintr.r-lib.org/reference/linters.html) as an option.   If any lint options are set, logrx will call lintr::lint() and passing in the linters.

### Relevant Output

A new section in the log that contains the lint results.

### Reproducible Example/Pseudo Code

```r
options(logrx.lint = c(undesirable_operator_linter(), absolute_path_linter()))

if ('logrx.lint' %in% names(options())) {
  lint_results <- lintr::lint(file, options('logrx.lint'))
  set_log_element("lint_results", lint_results)
}
```

**Comment by kodesiba** [comment]
I absolutely love this and think it could make a great addition!

**Comment by nicholas-masel** [comment]
> I absolutely love this and think it could make a great addition!

I'll branch out and add this in for review/consideration.
